"""Python serial number generator."""

class SerialGenerator:
    """Machine to create unique incrementing serial numbers.

    start:

    
    >>> serial = SerialGenerator(start=100)

    >>> serial.generate()
    100

    >>> serial.generate()
    101

    >>> serial.generate()
    102

    >>> serial.reset()

    >>> serial.generate()
    100
    """

    def __init__(self, start):
        """ Sets the initial value of serial generator to start"""
        self.start = self.value = start

    def __repr__(self):
        """string representation"""
        return f"<Serial Generator start={self.start} next={self.value} value"

    def generate(self):
        """return the new number generated by incrementing value by 1. """
        self.value += 1;
        return self.value

    def reset(self):
        """ resets the value to the start."""
        self.value = self.start
        return self.value
    

